### ISSUE TITLE
Breaking bug from sentry-javascript 6.1.0

### ISSUE THREAD

**Issue by michalmikolajczyk** [nuxt-community/sentry-module#280] opened 2021-03-08 11:58 UTC
### Is your feature request related to a problem? Please describe.
With the latest version of this module, we are experiencing a breaking bug, which was reported here a week ago https://github.com/getsentry/sentry-javascript/issues/3278

You can observe the bug here:
1. open in incognito https://freshcleantees-staging.herokuapp.com/
2. open developers console
3. do a hard-refresh
4. observe the error `TypeError: e.captureSession is not a function`

### Describe the solution you'd like
Revert back to version 5.2.6 until the bug is resolved

### Describe alternatives you've considered
This bug is breaking the integration, but is related to its core dependency. Reverting to a previous version allows this module to be used

**Comment by rchl** [comment] 2021-03-08 12:43
I suppose there is no action that this module can take here.

**Comment by michalmikolajczyk** [comment] 2021-03-08 13:08
Actually you can do a revert to the previous version of `sentry-javascript` so that we can use this module. The internal dependency is now locked at v `6.1.0` which is bugged

**Comment by rchl** [comment] 2021-03-08 13:31
I'm not sure if the issue is serious enough to warrant a rollback. As you said, there is always an option of rolling back to the older module version.

**Comment by rchl** [comment] 2021-03-08 19:11
It appears to be sessions-specific so I could disable session traffic for now I guess.

**Comment by michalmikolajczyk** [comment] 2021-03-09 10:22
Do you mean to disable performance monitoring?

**Comment by michalmikolajczyk** [comment] 2021-03-09 12:45
This seems to be a viable workaround. We will use this until the bug is resolved in https://github.com/getsentry/sentry-javascript/issues/3278

Thanks @rchl

**Comment by m-nathani** [comment] 2021-04-22 06:14
guys still getting this error in `"@sentry/browser": "^6.3.0",`
its urgent does anyone know how to fix it asap ?


here is the stack trace i found in minified version...
```javascript
e.captureSession(),ls({callback:function(){e.startSession(),e.captureSession()},type:"history"}))}()}
```

![Uploading Screenshot from 2021-04-22 13-59-31.png…]()

**Comment by rchl** [comment] 2021-04-22 06:25
@m-nathani you can disable session tracking as I've mentioned in https://github.com/nuxt-community/sentry-module/issues/280#issuecomment-793694611

**Comment by m-nathani** [comment] 2021-04-22 07:32
> @m-nathani you can disable session tracking as I've mentioned in [#280 (comment)](https://github.com/nuxt-community/sentry-module/issues/280#issuecomment-793694611)


Hi @rchl , i hope you are doing well.. 

adding `autoSessionTracking: false` to ``Sentry.init` method fix it .. however is this a permanent fix ?

It appears if mark it `false`  i wont have session tracking..

**Comment by rchl** [comment] 2021-04-22 07:34
It's a solution until the issue is fixed in the sentry SDK.

**Comment by rchl** [comment] 2021-08-19 13:53
Upstream seems to have fixed this. Feel free to reopen or create new issue if there is something left to do.

**Closed by rchl** 2021-08-19 13:53 UTC
Labels: feature-request
