### ISSUE TITLE
How do exclude sourcemap from production stage

### ISSUE THREAD

**Issue by kolesoffac** [nuxt-community/sentry-module#512] opened 2023-02-28 07:46 UTC
I use webpack plugin for publish release with code with sourcemap to Sentry in buildtime. But for production stage source map should be exclude.

How can do it?

**Comment by rchl** [comment] 2023-02-28 07:48
Duplicate of https://github.com/nuxt-community/sentry-module/issues/497 ?

**Closed** 2023-02-28 08:15 UTC
Labels: question
