### ISSUE TITLE
how to add custom transport to send captured error

### ISSUE THREAD

**Issue by glebv** [nuxt-community/sentry-module#439] opened 2022-08-26 12:29 UTC
Our Nuxt app uses a custom JS Error Logger. I'd want to use two ways(custom logger and sentry) to report errors while migration on sentry 
How to add a custom transport (additional way to send http request with captured errors) to nuxt-sentry integration?

**Comment by rchl** [comment] 2022-08-26 21:02
Doesn't seem possible right now.

I'm thinking that we could allow defining custom function that would receive resolved Sentry config before Sentry is initialized and could mutate it as it wishes.

So for example one of the module options would be `beforeSentryInit: '~/hooks/before-sentry-init.js'` and the function could look like:

```js
export default function(config) {
  config.transport = new SomeTransport(...);
  return config;
}
```

**Comment by glebv** [comment] 2022-08-29 14:16
@rchl thanks it works, but I realized that transport doesn't solve easy my problem. The main goal is to use Sentry and already developed JS error logger.  Sentry and our logger are based on utilization of the same `Vue.config.errorHandler`. And the one redefines others handler, that's the problem. Is the way to assign an additional custom handler 
 to `Vue.config.errorHandler` or to pass somehow error to the additional handler?

**Comment by rchl** [comment] 2022-12-17 22:34
Duplicate of #343

**Closed by rchl** 2022-12-17 22:34 UTC
Labels: question, feature-request
