### ISSUE TITLE
SENTRY_RELEASE cannot found in browser

### ISSUE THREAD

**Issue by Limsanity** [nuxt-community/sentry-module#173] opened 2020-04-20 16:35 UTC
I wonder why the sentry-webpack-plugin only included in server webpack config but not in client webpack config? Maybe avoid uploading files twice? sentry-webpack-plugin would auto set the release property to window.SENTRY_RELEASE according to sentry cli, so that developer dont have to set it in Sentry.init. And server side Sentry.init is called in module.js before webpack compile, so release cannot be auto set either.

**Comment by rchl** [comment] 2020-04-21 18:05
Yes, it's to avoid uploading files twice (or more if using modern build also).
We add it only in the last step, when all other bundles have already been created.
I didn't know that adding it has also other side effects. I would have to investigate if it's possible to add it in all steps but only upload in the last one... If you have time, you could help :)

**Comment by Limsanity** [comment] 2020-04-21 19:03
It seems not work if add it in all steps, because we can only get the SENTRY_RELEASE after webpack compiling, but server side Sentry.init is called before compile step. Also it seems no options to disable uploading in sentry-webpack-plugin.
Maybe we can get that release value by @sentry/cli library, like the code below:
```js
const SentryCli = require('@sentry/cli');
const cli = new SentryCli();
cli.releases.proposeVersion().then(version => {
    return version;
})
```
And then injected into both clientSide option and serverSide option.

**Comment by rchl** [comment] 2020-07-23 21:01
I'll resolve it as duplicate of #200.

**Closed by rchl** 2020-07-23 21:01 UTC
