### ISSUE TITLE
Error when publishRelease is enabled

### ISSUE THREAD

**Issue by joergac** [nuxt-community/sentry-module#65] opened 2019-03-17 10:07 UTC
### Version

[2.3.1](https://github.com/sentry-module/releases/tag/2.3.1)

### Reproduction link

[https://github.com/nuxt-community/sentry-module/issues/31](https://github.com/nuxt-community/sentry-module/issues/31)

### Steps to reproduce

Add publishRelease like so

```
sentry: {
    dsn: 'https://xxxxxxxxxxxx@sentry.io/xxxxxxx',
    publishRelease: true,
    options: {
      environment: env.SENTRY_ENV
    }
  },
```

### What is expected ?

Publish a release on push

### What is actually happening?

```

 [1m [31mERROR in Sentry CLI Plugin: Command failed: /home/forge/xxxxxx/node_modules/@sentry/cli/sentry-cli releases new xxxxxxd55334f3f4xxxxxxxxxxxxx
error: An organization slug is required (provide with --org)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
 [39m [22m

10:01:22  FATAL  Nuxt Build Error

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5262:15)
  at process._tickCallback (internal/process/next_tick.js:68:7)

```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/sentry-module/issues/c49">#c49</a>)</em></sub></div>

**Comment by williamchong007** [comment] 2019-03-25 13:31
You need to set the ENV required in https://docs.sentry.io/cli/configuration/#configuration-values or have a `. sentryclirc` with respective values
Probably should mention it in the doc and provide a better error message/option though

**Comment by joergac** [comment] 2019-03-25 14:42
You are right @williamchong007! Thanks. 

Managed to solve this by creating the file `.sentryclirc` in my root with this contents.

```
[defaults]
project=xxxx
org=xxxx
[auth]
token=xxxxxxxxxxxxxx
```

The only thing left is to associate the commits according to this https://docs.sentry.io/workflow/releases/?platform=javascript#associate-commits-with-a-release

I linked the github repository (via sentry backend) but did not manage to successfully link the commits to the release. 

I suppose there should be a way to do that with https://github.com/getsentry/sentry-webpack-plugin but I scanned their options and it doesn't seem to have any related option.

**Comment by williamchong007** [comment] 2019-03-28 03:43
https://github.com/getsentry/sentry-webpack-plugin/issues/55#issuecomment-387320764
It should happen automatically if you are inside a git repo

**Comment by joergac** [comment] 2019-04-02 21:30
It doesn't work like this though.

This is my config
```
  sentry: {
    dsn: 'https://xxxx@sentry.io/xxx',
    publishRelease: true,
    config: {
      environment: env.SENTRY_ENV
    }
  },
```

No commits are associated to the release.

**Comment by joergac** [comment] 2019-04-02 22:07
Doing this directly in my repository through ssh works fine..

```
$ VERSION=`npx ./node_modules/@sentry/cli/sentry-cli releases propose-version`
$ echo $VERSION //returns 5c7dfg0f81385b28bdb5f12359489a933eeab4574
$ npx ./node_modules/@sentry/cli/sentry-cli releases new -p frontend "$VERSION" // Created release 5c7dfg0f81385b28bdb5f12359489a933eeab4574.
$ npx ./node_modules/@sentry/cli/sentry-cli releases set-commits --auto "$VERSION"

+----------------------+--------------+
| Repository           |    Revision  | 
+----------------------+--------------+
| xxxxxx/frontend      |     xxxxxx   |
+----------------------+--------------+
```

**Comment by rchl** [comment] 2019-04-03 05:51
If you are not passing version identifier to `moduleOptions.config.release` then when sentry initializes at runtime, it won't be able to figure out release. There is no git repo at runtime from which it could get commit information.

So what you want is to specify `moduleOptions.config.release`. I'm setting it to version form package json:
```js
const packageJson = require('./package.json');
```
and in nuxt-config.js:
```js
        ['@nuxtjs/sentry', {
            config: {
                environment: process.env.ENV,
                release: packageJson.version,
                dsn: process.env.SENTRY_DSN,
                disabled: isDevelopment,
            },
            dsn: process.env.SENTRY_DSN,
            disabled: isDevelopment,
            publishRelease: true,
        }],
```
(notice `release` property is set to app version.

Then there is one changed needed in the module to also pass that release version to webpack config per https://docs.sentry.io/platforms/node/sourcemaps/

**Comment by aldarund** [comment] 2019-04-17 22:57
Closing as not a bug in module, but rather a configuration error

**Comment by rchl** [comment] 2022-02-20 21:03
This was resolved at some point - https://sentry.nuxtjs.org/sentry/options#publishrelease

**Closed by rchl** 2022-02-20 21:03 UTC
Labels: bug
