### ISSUE TITLE
Unable to use custom integrations

### ISSUE THREAD

**Issue by alexcroox** [nuxt-community/sentry-module#435] opened 2022-08-02 14:25 UTC
### Version
@nuxtjs/sentry: 5.1.7
nuxt: 2.15.8

### What is Expected?

I'm trying to implement [PostHog's custom Sentry integration](https://posthog.com/docs/integrate/third-party/sentry) but after digging through the source of this module, it seems config.integrations is overwritten by a hardcoded filter list of allowed integrations.

It seems it's not possible to use custom integrations.

```
integrations: [new posthog.SentryIntegration(posthog, 'your organization', project-id)],
```

**Comment by rchl** [comment] 2022-08-02 14:32
I have unfinished PR for supporting external integrations - https://github.com/nuxt-community/sentry-module/pull/276

**Comment by rchl** [comment] 2022-08-02 19:52
Duplicate of #240

**Closed by rchl** 2022-08-02 19:52 UTC
Labels: bug
