### ISSUE TITLE
running npm install @nuxtjs/sentry doesn't work

### ISSUE THREAD

**Issue by sarwan920** [nuxt-community/sentry-module#419] opened 2022-05-09 05:05 UTC
I recently switched my laptop and cloned my project which was already  working fine on the other laptop, when I installed node js in new laptop with version v16.15.0 and tried running "npm install" in my nuxt project as you can see in screen shot below. and gives error while installing @nuxtjs/sentry
![npm error](https://user-images.githubusercontent.com/47607107/167343818-81190656-59a0-43d9-aa65-f5d31020bca9.png)

also removing sentry package from package.json and nuxt.config.js and then running npm install to have all other dependencies works just fine.

And running "npm install @nuxtjs/sentry" gives the same error too.

**Comment by sarwan920** [comment] 2022-05-09 06:56
I couldn't find the solution but came to know its not issue with NodeJS version.

please if someone can guide about solution.

**Comment by kissu** [comment] 2022-05-09 07:03
Hi, don't close the issue is related to the package.

**Comment by sarwan920** [comment] 2022-05-09 07:05
> Hi, don't close the issue is related to the package.
I have reopened it. I have know idea whats causing this.

**Comment by kissu** [comment] 2022-05-09 07:06
I've asked more info on SO. But a reproduction could be helpful on both sides. I could try that on my machine if it's not private.

**Comment by sarwan920** [comment] 2022-05-09 07:11
Actually, on my older machine which already has working project with @nuxtjs/sentry and node version v14.17.5 and I tried @nuxtjs/sentry on older machine in other project and installed successfully.

but i tried installing same Nodejs version on my new machine and try installing nuxt sentry with that version but got the same issue.

**Comment by kissu** [comment] 2022-05-09 07:13
All of my previous are still valid (regarding debugging).

Also, what do you use to manage your node.js version? Double checked the currently used one with `node -v`?

**Comment by sarwan920** [comment] 2022-05-09 07:15
Thats my questions actually, i asked both here and stackoverflow

**Comment by kissu** [comment] 2022-05-09 07:23
Yeah I know, I'm the same guy.

Please read all of my previous questions and please answer to some of them.

**Comment by sarwan920** [comment] 2022-05-09 07:29
I probably think this issue is with my machine and installed windows, because i tried installing totally first time node js on another persons windows machine and tried "npm install @nuxtjs/sentry" it installed successfully without any issue.

**Comment by kissu** [comment] 2022-05-09 07:30
I cannot help you if you only make suppositions without answering to some questions.
"Yeah maybe, who knows" is my current answer regarding the windows + node issue you're mentioning.

**Comment by sarwan920** [comment] 2022-05-09 07:36
I can't answer properly because the issue I am getting is only on one machine, I tried same exact method on other machines for installing @nuxtjs/sentry and got no issue.

I came across issue multiple times on my new machine after installing and uninstalling different node js versions. still my machine is the only one facing this issue so I don't think this is the issue with the actual package.

**Comment by kissu** [comment] 2022-05-09 07:43
Still, you can answer those:
- what do you have when typing `node -v`?
- what do you use `nvm` or something else to manage your node.js versions?

**Comment by sarwan920** [comment] 2022-05-09 07:46
- what do you have when typing node -v?
v16.15.0

- what do you use nvm or something else to manage your node.js versions?
Actually I am not super experienced can you explain what do you mean by this question?

As i have only 1 version installed of NodeJS which is v16.15.0. I have no idea what other info do you need?
If you could guide more i would be grateful.

**Comment by kissu** [comment] 2022-05-09 07:49
Try installing nvm to get an easier time with your node.js versions. You may need several at some point and this will help you debug the whole thing faster. 

https://github.com/nvm-sh/nvm

**Comment by sarwan920** [comment] 2022-05-09 07:51
Okay Thanks, I will look into this.

**Comment by kissu** [comment] 2022-05-09 09:20
Do you have a reproduction or a Github repo (public)?

**Comment by sarwan920** [comment] 2022-05-09 09:25
No, I do not. facing this issue in private repo that I can't share actually.

I also tried like creating new folder
and running "npm init" to create package.json

and then running inside that npm install @nuxtjs/sentry gave the same exact error.

**Comment by rchl** [comment] 2022-05-09 09:38
Maybe try manually deleting `C:\Users\...\AppData\Local\npm-cache` and then try again.

If that fails, try running `npx sentry-cli --version` in your terminal.

**Comment by sarwan920** [comment] 2022-05-09 09:58
> Maybe try manually deleting `C:\Users\...\AppData\Local\npm-cache` and then try again.
> 
> If that fails, try running `npx sentry-cli --version` in your terminal while being inside your project.

I did delete npm-cache folder and then I ran npm install @nuxtjs/sentry and I got this 
![image](https://user-images.githubusercontent.com/47607107/167386852-5ec3503b-026a-431b-b4ec-9c7e4042ad64.png)
![image](https://user-images.githubusercontent.com/47607107/167386956-63ca03f2-b9d5-4180-91c2-2e31527577b9.png)

Two images of error attached

**Comment by sarwan920** [comment] 2022-05-09 17:49
@rchl @kissu can someone guide like if this is issue related to the package or something else that I am missing.

because only on my 1 machine i am unable to install this package, and also installing every other package from npm works just fine without any issues.

**Comment by sarwan920** [comment] 2022-05-10 07:42
Just sharing comment here that trying to install package using yarn failed too.

**Comment by kissu** [comment] 2022-05-10 08:04
I did not get that sentence. `Sharing comment`?
Didn't `yarn` gave you more details about the error?
Maybe time to uninstall everything and install it again.

**Comment by sarwan920** [comment] 2022-05-10 08:18
Sharing comment I meant mentioning that installing through yarn didn't work.
and there is not much information on yarn error too check the attached screenshot.

![image](https://user-images.githubusercontent.com/47607107/167580406-b33733b3-0314-493f-9799-941069405fef.png)

and I have litrelly reinstalled windows 3 times, and different versions of node js but the same error

**Comment by rchl** [comment] 2022-05-10 08:20
Those two dots before `sentry-cli.exe` don't look right to me but not sure why would that be the case.

**Comment by kissu** [comment] 2022-05-10 08:21
Try to use `nvm` to manage the node.js version, otherwise maybe look into the [CLI](https://docs.sentry.io/product/cli/) if it's really that needed.

**Comment by sarwan920** [comment] 2022-05-11 06:28
I am closing the issue because it successfully installed now, I have no idea how it got fixed, I just ran "npm install @nuxtjs/sentry" today, and it worked without issues

**Comment by kissu** [comment] 2022-05-11 06:31
Probably because it asked you to restart the terminal to apply some changes. Now that you have rebooted, it works (because of PATH etc).

**Closed** 2022-05-11 06:30 UTC
Labels: question

**Comment by sarwan920** [comment] 2022-05-11 06:36
I had already done that multiple times before, even restarted the system, but today it just worked
