### ISSUE TITLE
delayedCalls is undefined when using lazy: true

### ISSUE THREAD

**Issue by alexcroox** [nuxt-community/sentry-module#348] opened 2021-09-16 19:23 UTC
### Version
@nuxtjs/sentry: 5.1.3
nuxt: 2.15.8

### Sentry configuration
<!--
    If relevant, please include the configuration you are using for this module.
```
-->
```
sentry: {
    disabled: process.env.APP_ERROR_REPORTING_ENABLED === 'false',
    lazy: true,
    publishRelease: false,
    config: {
      environment: process.env.VUE_APP_ENVIRONMENT || 'production',
      release: appVersion
    }
  },
```

### Steps to reproduce

Enable lazy mode

### What is Expected?

No errors

### What is actually happening?

Occasionally I get this error:

![image](https://user-images.githubusercontent.com/1065835/133672786-bcbc9db3-d771-431b-a3ba-15e1d4f15bcf.png)

Ignore the LogRocket mentions, it's just capturing it. 

![image](https://user-images.githubusercontent.com/1065835/133672850-49f7f8e1-87d8-4b51-af9c-9571a6710d95.png)

I traced it back to this line: https://github.com/nuxt-community/sentry-module/blob/master/lib/plugin.lazy.js#L48

**Comment by alexcroox** [comment] 2021-09-16 19:25
I'm guessing because I'm not using injectMock the variable never get's initiated? 

https://github.com/nuxt-community/sentry-module/blob/master/lib/plugin.lazy.js#L3-L5

**Comment by rchl** [comment] 2021-09-16 20:51
> Ignore the LogRocket mentions, it's just capturing it.
> 
> ![image](https://user-images.githubusercontent.com/1065835/133672850-49f7f8e1-87d8-4b51-af9c-9571a6710d95.png)

Can you check a bit above this place whether the `oe` variable is defined?

The `oe` variable should be in scope so not sure why it would crash here. Both the variable and this code are only included if `injectMock` is enabled.

**Comment by alexcroox** [comment] 2021-09-17 10:46
sure here is the relevant output from that production bundle, it looks OK to me...

```
var te,
    oe = [
    ],
    re = {
    },
    ae = !1,
    ie = !1,
    ne = [
    ],
    se = [
    ],
    le = function (e) {
      ne.push([e.message,
      e.filename,
      e.lineno,
      e.colno,
      e.error])
    },
    ce = function (e) {
      se.push('reason' in e ? e.reason : 'detail' in e && 'reason' in e.detail ? e.detail.reason : e)
    },
    de = i['default'].config.errorHandler;
    function ue(e, t) {
      [
        'addGlobalEventProcessor',
        'addBreadcrumb',
        'captureException',
        'captureEvent',
        'captureMessage',
        'configureScope',
        'getHubFromCarrier',
        'getCurrentHub',
        'Hub',
        'makeMain',
        'Scope',
        'startTransaction',
        'setContext',
        'setExtra',
        'setExtras',
        'setTag',
        'setTags',
        'setUser',
        'withScope',
        'BrowserClient',
        'injectReportDialog',
        'eventFromException',
        'eventFromMessage',
        'forceLoad',
        'init',
        'lastEventId',
        'onLoad',
        'showReportDialog',
        'flush',
        'close',
        'wrap'
      ].forEach((e=>{
        re[e] = function () {
          for (var t = arguments.length, o = new Array(t), r = 0; r < t; r++) o[r] = arguments[r];
          return oe.push([e,
          o])
        }
      })),
      window.addEventListener('error', le),
      window.addEventListener('unhandledrejection', ce),
      t('sentry', re),
      e.$sentry = re;
      window.onNuxtReady((() =>function (e, t) {
        return pe.apply(this, arguments)
      }(e, t)));
      var o = new Promise((e=>{
        te = e
      })),
      r = () =>o;
      t('sentryReady', r),
      e.$sentryReady = r
    }
```

**Comment by alexcroox** [comment] 2021-09-17 10:53
I believe the previous step in the trace:

```
window.LogRocket.getSessionURL((e=>{
  r.configureScope((t=>{
    t.setExtra('sessionURL', e)
  }))
}))
```

**Comment by rchl** [comment] 2021-09-17 11:14
I think I know what's happening. With lazy loading, we are initially creating a mocked $sentry object. It's the one where the `oe` related error triggers. Once the actual sentry loads, we overwriting that mock object with the sentry one and unset the `delayedCalls` variable (the `oe` one in minified code).

So if some code holds onto that initial mocked reference and tries to call it later, it would cause that exact issue.

Relevant code from logrocket module: https://github.com/nuxt-community/nuxt-logrocket/blob/4a43cd2e79e0a100f39a608950e6285e72c1a926/lib/plugin.js#L27-L34

I'm kinda surprised that our `forceInject` (https://github.com/nuxt-community/sentry-module/blob/98844119a6e51ab8c2fa03b88bce8d3760ba48a7/lib/plugin.lazy.js#L199-L204) doesn't update the `app.$sentry` in the context of the logRocket module... Maybe Nuxt sends a copy of the object to each plugin... Not sure from the top of my head how this could be fixed. Have to think about it when I have more time.

**Comment by rchl** [comment] 2021-09-17 20:05
I can't actually reproduce locally but looking at your minified code:

> ```
> window.LogRocket.getSessionURL((e=>{
>   r.configureScope((t=>{
>     t.setExtra('sessionURL', e)
>   }))
> }))
> ```

this is indeed the reason. It's quite aggressively minified compared to mine:

```
                  (console.log('has sentry'),
                   setTimeout(
                       (function(t) {
                         n.$sentry.configureScope((function(e) {
                           e.setExtra('sessionURL', t)
                         }))
                       }),
                       1)),
``` 

Note that I've modified the code slightly since I don't have valid logRocket ID but you can see that in my case the `app.$sentry` is not cached into a local variable so everything works. In your case the minified code does something like `var t = app.$sentry` earlier so it holds to mocked `$sentry` reference and uses it even after `app.$sentry` was updated.

Have you modified any of the babel or terser settings in your nuxt config?

**Comment by klausXR** [comment] 2022-01-07 08:43
I am also experiencing this issue. I believe its related to asynchrony of some sort. The problematic line for me is 

```
SentryMock[key] = (...args) => delayedCalls.push([key, args])
```

This gets called after `delayedCalls = undefined`, so it throws an error. 

The problem is likely related to asynchrony. What I believe is happening ( I havent read the code in its entirety ) is that an error is scheduled for reporting through the mock, but is currently waiting in the queue ( it will execute on the next tick )

The line of code where you are calling `sentryReadyResolve(Sentry)` is an async operation, so it gets dispatched to the queue. Then, immediately after that this code follows

```js
  // help gc
  <% if (options.lazy.injectMock) { %>
  // Dont unset delayedCalls & SentryMock during
  // development, this will cause HMR issues
  <% if (!options.dev) { %>
  delayedCalls = undefined
  SentryMock = undefined
  <% } else { %>
  delayedCalls = []
  <% } %>
  <% } %>
  sentryReadyResolve = undefined
  ```
  
Where the `delayedCalls` is set to `undefined`. Now, the `delayedCalls` is undefined, but on the next tick there is a report scheduled that uses this variable, so when it executes, its going to throw an error

**Comment by rchl** [comment] 2022-01-07 09:00
I've already proved that the issue is due to weird (incorrent) code minifying. If you can share a project that reproduces then I could look deeper into it but it feels like a bug in babel/webpack that is probably already resolved in latest versions.

**Comment by klausXR** [comment] 2022-01-07 10:13
I'm using the latest 2.15.8 version, which requires 4.46 webpack and this module does not work for me, so I'm not sure how I'm supposed to update anything to get it to work, in cases where its due to wrong dependencies

**Comment by rchl** [comment] 2022-01-07 10:16
I meant mostly sub-dependencies of babel. Either that or some custom babel configuration that causes this.

In any case, if you don't provide a project that reproduces then I won't be able to help you more.

**Comment by rchl** [comment] 2022-02-20 21:16
Closing due to there not being enough information to reproduce and fix.
And it doesn't reproduce with default config so it's assumed to be a corner case due to some local babel overrides or outdated dependencies.

**Closed by rchl** 2022-02-20 21:16 UTC
Labels: question, awaiting reporter input

**Comment by adamlachmann** [comment] 2022-03-06 22:42
Same thing happens for me when using [nuxt/composition-api](https://github.com/nuxt-community/composition-api).  The solution was to use instance of `$sentry` in `context.app` not `context` directly, as that one seem to retain the mocked sentry plugin.

```ts
import { useContext } from '@nuxtjs/composition-api'
...
const context = useContext()

context.$sentry.captureException(new Error()) // fails
context.app.$sentry.captureException(new Error()) // works properly
```

**Comment by rchl** [comment] 2023-08-11 14:22
This issue also hit me now so since I was able to reproduce I've added a workaround in https://github.com/nuxt-community/sentry-module/pull/606 and released in https://github.com/nuxt-community/sentry-module/releases/tag/v7.4.0

Ideally the code wouldn't hold the reference to `context.$sentry` and always get it from `context` and then the issue wouldn't trigger but I guess it's not obvious that this can cause issues.
