### ISSUE TITLE
Exception on build stage: SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by VladStepanov** [nuxt-community/sentry-module#491] opened 2023-01-16 11:54 UTC
### Version
@nuxtjs/sentry: 7.0.2
nuxt: 2.14.11

### Sentry configuration
Just include '@nuxtjs/sentry' in modules array.

### Reproduction Link
Private repo, i can't

### Steps to reproduce
```sh
yarn add @nuxtjs/sentry
```

Append `'@nuxtjs/sentry'` to modules in `nuxt.config.js`.
```js
modules: [
  ...
  '@nuxtjs/sentry'
]
```

Add configuration
```js
sentry: {
  dsn: '...'
}
```

### What is Expected?
Success build

### What is actually happening?
Error on build stage.
<img width="678" alt="image" src="https://user-images.githubusercontent.com/49880862/212672182-0dc6612e-82f5-438d-9366-4955b184f799.png">

**Comment by rchl** [comment] 2023-01-16 12:52
This looks like a code from the `mlly` package that was added recently. The issue is really with the old version of Nuxt that you are using that is not able to handle modern JS syntax. I would suggest that you upgrade your Nuxt version.

**Comment by VladStepanov** [comment] 2023-01-16 13:58
@rchl 
I tried @nuxtjs/sentry@7.0.0 and @nuxtjs/sentry@7.0.1. This works. Exception happens only in 7.0.2

**Comment by rchl** [comment] 2023-01-16 14:46
Yes, because `mlly` was added in 7.0.2.

Latest Nuxt 2 version (currently 2.15.8) should support this fine so I'm closing this issue since I'm not planning to support old versions.

**Closed** 2023-01-16 14:46 UTC
Labels: question
